from . import account_asset_use_state
from . import account_asset_asset
from . import account_asset_location
from . import account_asset_movement
from . import hr_department
from . import hr_employee
from . import product_template
from . import account_asset_attribute
from . import stock_warehouse
from . import product
