# -*- coding: utf-8 -*-
{
    'name': "Construction Management System",
    'version': "1.0",
    'summary': """
    Project Management, 
    Construction, 
    Tenders, 
    Owner Contract, 
    Subcontractor, 
    Subcontractor Contract,
    Construction Management System (CMS), 
    Completion Request, 
    Tasks, delivery requests, 
    Work Breakdown Structure (WBS), 
    Work Breakdown Template (WBT),
    units, 
    jobs, 
    Dashboard""",

    'description': """A Construction Management System (CMS) is a comprehensive software solution designed to 
    streamline and optimize the various processes involved in construction projects. It serves as a centralized 
    platform to facilitate collaboration, communication, and data management throughout the entire lifecycle of a 
    construction project.""",

    'category': 'Project',
    'author': 'Neoteric Hub',
    'company': 'Neoteric Hub',
    'live_test_url': '',
    'price': 799,
    'currency': 'USD',
    'website': 'https://www.neoterichub.com',

    'depends': ['hr', 'account', 'purchase', 'product', 'project', 'contacts', 'hr_expense', 'board'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/project_unit_type.xml',
        'data/contract_seq.xml',
        'views/hr_expense.xml',
        'data/sub_contract_delivery_request_seq.xml',
        'data/project_engineer_technical_sequence.xml',
        'data/job_cost_sequence.xml',
        'data/wbs_cost_sequence.xml',
        'data/stages_demo.xml',
        'data/product_template_demo.xml',
        'data/tender_job_cost_demo.xml',
        'data/tender_item_demo.xml',
        'wizards/new_wbs_wizard_view.xml',
        'views/construction_project.xml',
        'views/contract.xml',
        'views/stages.xml',
        'views/project_unit_type.xml',
        'views/tender_job.xml',
        'views/tender_item.xml',
        'views/contract_completion_request.xml',
        'views/contract_deduction_allowance.xml',
        'views/sub_contract_deduction_allowance.xml',
        'views/contract_completion_deduction_allowance.xml',
        'views/project_wbs.xml',
        'views/sub_contract_delivery_request.xml',
        'views/tender_job_cost_view.xml',
        'views/wbs_job_cost.xml',
        'views/product_views.xml',
        'views/dashboard.xml',
        'views/partner_view.xml',
        'views/menu_views.xml',
        'report/delivery_request.xml',
        'report/hr_expense_report.xml',
        'report/contract_report.xml',
        'report/completion_request_report.xml',
    ],
    'demo': [
        'demo/demo.xml',
    ],
    'images': ['static/description/banner.gif'],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}
